// Artigos para quem bate ponto (todo mundo), para o gestor e para quem não
// consegue entrar. Mesmo formato de artigosGestao.js.
// Links pessoais usam "rota:chave": o endereço muda para administrador e RH.

const ARTIGOS_PESSOAIS = [
  // ------------------------------------------------------------- Ponto
  {
    id: 'bater-ponto',
    categoria: 'ponto',
    publico: ['colaborador'],
    titulo: 'Como bater o ponto',
    resumo: 'Entrada, intervalo e saída em um toque.',
    palavras: ['bater ponto', 'registrar', 'marcar', 'entrada', 'saida', 'intervalo', 'almoco', 'marcacao'],
    telas: ['/', '/gestao/meu-ponto'],
    corpo: [
      'Abra a tela de [registro de ponto](rota:ponto). Administrador e RH também podem usar o botão **Registrar ponto**, no alto da tela.',
      { tipo: 'passos', itens: [
        'Confira a sugestão: **Próxima marcação esperada** (por exemplo, Entrada).',
        'Toque no botão grande, como **Registrar entrada**.',
        'Pronto: aparece o comprovante com o horário e o NSR.',
      ] },
      'São quatro marcações por dia: **Entrada**, **Início do intervalo**, **Fim do intervalo** e **Saída**.',
      { tipo: 'dica', texto: 'A sugestão errou? Toque em **Registrar outro tipo** e escolha o tipo certo. A sugestão nunca bloqueia nada.' },
      { tipo: 'lista', itens: [
        'O horário vem do servidor do Ayra, não do relógio do celular.',
        'A localização é opcional: se você não permitir, o ponto é registrado igual.',
        'É preciso estar com internet na hora de bater o ponto.',
      ] },
      { tipo: 'atencao', texto: 'Apareceu "Sua conta ainda não está ligada a uma unidade"? Fale com o RH da sua empresa para liberar o registro.' },
    ],
  },
  {
    id: 'comprovante',
    categoria: 'ponto',
    publico: ['colaborador'],
    titulo: 'Comprovante e NSR',
    resumo: 'O que é o comprovante de cada marcação e como ver de novo.',
    palavras: ['comprovante', 'nsr', 'recibo', 'codigo de integridade', 'prova', 'pdf', 'assinatura', 'baixar'],
    telas: ['/', '/gestao/meu-ponto'],
    corpo: [
      'A cada marcação você recebe um comprovante com data, hora, **NSR**, seu nome e CPF, a empresa, a unidade e um código de integridade.',
      { tipo: 'lista', itens: [
        '**NSR** é o número sequencial da marcação na sua unidade. Ele nunca se repete.',
        'O **código de integridade** garante que a marcação não foi alterada depois.',
      ] },
      'Para ver um comprovante de novo, toque no **NSR** da marcação, no cartão **Marcações de hoje**.',
      { tipo: 'sub', titulo: 'Comprovante em PDF' },
      'No comprovante, toque em **Baixar comprovante em PDF**. No seu [histórico](rota:historico), cada marcação tem um botão de PDF ao lado do NSR. O PDF é o **Comprovante de Registro de Ponto do Trabalhador** da Portaria 671, com assinatura digital, e fica disponível para todas as suas marcações.',
      { tipo: 'dica', texto: 'O comprovante mostra o CPF mascarado. Se aparecer "não informado", peça ao RH para cadastrar o seu CPF.' },
    ],
  },
  {
    id: 'comprovante-email',
    categoria: 'ponto',
    publico: ['colaborador'],
    titulo: 'Comprovante por e-mail',
    resumo: 'O PDF de cada marcação chega no seu e-mail. Como ligar ou desligar.',
    palavras: ['comprovante', 'email', 'e-mail', 'pdf', 'nao chegou', 'desligar', 'receber', 'spam', 'caixa de entrada'],
    telas: ['/conta', '/gestao/conta'],
    corpo: [
      'A cada marcação, o **Comprovante de Registro de Ponto do Trabalhador** em PDF, com assinatura digital, vai para o **e-mail com que você entra** no Ayra Ponto.',
      'Normalmente chega em poucos minutos. Se a internet cair logo depois da marcação, o envio é refeito sozinho, a cada 5 minutos.',
      { tipo: 'sub', titulo: 'Ligar ou desligar' },
      'Em [Minha conta](rota:conta), no cartão **Comprovante por e-mail**, marque ou desmarque **Receber o comprovante de cada marcação**. Vem ligado.',
      'Desligado, nada se perde: o comprovante continua na tela e no seu [histórico](rota:historico), com o botão de PDF.',
      { tipo: 'sub', titulo: 'Não chegou?' },
      { tipo: 'lista', itens: [
        'Olhe as pastas **Spam**, **Lixo eletrônico** e **Promoções**.',
        'Confira em Minha conta se o envio está ligado e se o e-mail mostrado é o seu.',
        'Baixe o PDF pelo seu histórico enquanto isso: é o mesmo comprovante.',
      ] },
      { tipo: 'dica', texto: 'O e-mail é o mesmo do login. Para trocar, fale com o RH da sua empresa.' },
    ],
  },
  {
    id: 'cadastrar-rosto',
    categoria: 'facial',
    publico: ['colaborador'],
    titulo: 'Cadastrar meu rosto',
    resumo: 'Quando a empresa usa reconhecimento facial: como tirar a foto de cadastro.',
    palavras: ['rosto', 'foto', 'selfie', 'reconhecimento facial', 'camera', 'cadastrar rosto', 'biometria'],
    telas: ['/conta', '/gestao/conta'],
    corpo: [
      'Se a sua empresa usa reconhecimento facial, cadastre o rosto antes da primeira marcação.',
      { tipo: 'passos', itens: [
        'Abra [Minha conta](rota:conta) e vá no cartão **Reconhecimento facial**.',
        'Toque em **Cadastrar meu rosto** e leia o aviso **Como usamos o seu rosto**.',
        'Fique num lugar bem iluminado, sem boné, óculos escuros ou máscara, com o celular na altura dos olhos.',
        'Olhe para a câmera e pisque quando pedir. Toque em **Usar esta foto**.',
        'O RH confere a foto. Você recebe o aviso no sininho.',
      ] },
      'Enquanto a foto não é aprovada, você bate o ponto normalmente.',
      { tipo: 'atencao', texto: 'A câmera foi bloqueada? Toque no cadeado ao lado do endereço do site e permita a câmera.' },
      { tipo: 'dica', texto: 'O reconhecimento facial nunca impede o ponto. Se a câmera falhar, use **Registrar sem foto**: a marcação vale e o RH confere depois.' },
    ],
  },
  // ------------------------------------------------------------- Pedidos
  {
    id: 'esqueci-ponto',
    categoria: 'pedidos',
    publico: ['colaborador'],
    titulo: 'Esqueci de bater o ponto ou bati no horário errado',
    resumo: 'Como pedir para incluir ou corrigir uma marcação.',
    palavras: ['esqueci', 'esquecimento', 'ajuste', 'corrigir', 'horario errado', 'incluir marcacao', 'faltou marcacao'],
    telas: ['/historico', '/gestao/meu-historico', '/espelho', '/gestao/meu-espelho'],
    corpo: [
      { tipo: 'passos', itens: [
        'Abra o seu [histórico](rota:historico) e toque em **Pedir ajuste** (ou em **Pedir ajuste deste dia**, no dia certo).',
        'Escolha **Esqueci de bater o ponto** para incluir uma marcação que faltou, ou **Bati no horário errado** para corrigir uma marcação.',
        'Informe o dia, o horário e qual marcação é.',
        'Escreva o motivo e toque em **Enviar pedido**.',
      ] },
      'O seu gestor ou o RH analisa. A resposta chega no sininho e em [Meus pedidos](rota:pedidos).',
      { tipo: 'lista', itens: [
        'A sua marcação original **nunca é apagada**. O ajuste aprovado aparece no espelho com um lápis.',
        'Dá para pedir ajustes dos últimos 90 dias.',
      ] },
      { tipo: 'dica', texto: 'O sininho avisa quando falta uma marcação nos últimos dias. Assim fica fácil lembrar.' },
    ],
  },
  {
    id: 'abono-atestado',
    categoria: 'pedidos',
    publico: ['colaborador'],
    titulo: 'Pedir abono com atestado',
    resumo: 'Faltou ou atrasou com justificativa? Peça o abono e anexe o documento.',
    palavras: ['abono', 'atestado', 'medico', 'declaracao', 'justificar falta', 'consulta', 'doente'],
    telas: ['/historico', '/gestao/meu-historico'],
    corpo: [
      { tipo: 'passos', itens: [
        'Abra o seu [histórico](rota:historico) e toque em **Pedir ajuste**.',
        'Escolha **Abonar falta ou atraso**.',
        'Informe o primeiro dia e, se for mais de um, o último.',
        'Em **Atestado ou declaração**, toque em **Escolher arquivo ou tirar foto**.',
        'Escreva o motivo e toque em **Enviar pedido**.',
      ] },
      { tipo: 'lista', itens: [
        'O anexo pode ser PDF ou foto (JPG, PNG ou WEBP), de até 5 MB.',
        'Só você, o RH e o administrador abrem o arquivo. O gestor não vê.',
        'Quem analisa o abono é sempre o RH.',
      ] },
      { tipo: 'atencao', texto: 'Não precisa escrever o diagnóstico no motivo.' },
    ],
  },
  {
    id: 'pedir-folga',
    categoria: 'pedidos',
    publico: ['colaborador'],
    titulo: 'Pedir folga',
    resumo: 'Dias em que você não vai trabalhar, combinados com a empresa.',
    palavras: ['folga', 'day off', 'dia livre', 'compensar', 'ausencia'],
    telas: ['/historico', '/gestao/meu-historico'],
    corpo: [
      { tipo: 'passos', itens: [
        'Abra o seu [histórico](rota:historico) e toque em **Pedir ajuste**.',
        'Escolha **Pedir folga**.',
        'Informe o primeiro e o último dia.',
        'Escreva o motivo e toque em **Enviar pedido**.',
      ] },
      'O seu gestor ou o RH analisa. Aprovada, a folga aparece no espelho como **Folga aprovada** e não vira falta.',
      { tipo: 'dica', texto: 'Cada pedido pode ter até 60 dias.' },
    ],
  },
  {
    id: 'acompanhar-pedidos',
    categoria: 'pedidos',
    publico: ['colaborador'],
    titulo: 'Acompanhar e cancelar meus pedidos',
    resumo: 'Ver a situação, a resposta e cancelar um pedido que ainda não foi analisado.',
    palavras: ['meus pedidos', 'cancelar pedido', 'resposta', 'aguardando', 'recusado', 'aprovado'],
    telas: ['/historico', '/gestao/meu-historico'],
    corpo: [
      'Em [Meus pedidos](rota:pedidos) aparece cada pedido com a situação: **Aguardando análise**, **Aprovada**, **Recusada** ou **Cancelada**, e a resposta de quem analisou.',
      { tipo: 'lista', itens: [
        'Enquanto o pedido espera análise, você pode tocar em **Cancelar pedido**. Ele fica no histórico como Cancelada.',
        'Pedido já analisado não pode ser cancelado. Se precisar, faça um novo.',
        'Você pode ter até 20 pedidos esperando análise ao mesmo tempo.',
      ] },
    ],
  },
  // ------------------------------------------------------------- Horas
  {
    id: 'espelho',
    categoria: 'horas',
    publico: ['colaborador'],
    titulo: 'Entender o meu espelho de ponto',
    resumo: 'O que significa cada coluna, situação e aviso do mês.',
    palavras: ['espelho', 'folha de ponto', 'horas', 'saldo', 'falta', 'incompleto', 'hora extra', 'atraso', 'lapis', 'imprimir'],
    telas: ['/espelho', '/gestao/meu-espelho'],
    corpo: [
      'O [espelho](rota:espelho) mostra o mês dia a dia: as marcações, o previsto pela jornada, o trabalhado, o que ficou a menos, as extras e o saldo.',
      { tipo: 'lista', itens: [
        '**Em dia:** trabalhou o previsto (dentro da tolerância).',
        '**Horas a menos** ou **Hora extra:** trabalhou menos ou mais que o previsto.',
        '**Falta:** dia de trabalho sem nenhuma marcação.',
        '**Incompleto:** falta uma entrada ou uma saída. O saldo do dia aparece como "?".',
        '**Abonado, Folga aprovada, Feriado, Férias, Atestado:** o dia não conta como falta.',
      ] },
      'Dias com problema mostram um aviso e o botão **Pedir ajuste**. Marcações com um **lápis** foram ajustadas por pedido aprovado. A original continua guardada.',
      { tipo: 'dica', texto: 'Use **Imprimir ou salvar em PDF** para ter a folha do mês.' },
    ],
  },
  {
    id: 'meu-banco',
    categoria: 'horas',
    publico: ['colaborador'],
    titulo: 'Meu banco de horas',
    resumo: 'Saldo, horas que vencem e extrato.',
    palavras: ['banco de horas', 'saldo', 'credito', 'vencer', 'compensar', 'extrato'],
    telas: ['/espelho', '/gestao/meu-espelho'],
    corpo: [
      'Em [Espelho](rota:espelho), aba **Banco de horas**, aparecem o saldo, as horas que vencem em 30 dias, as vencidas e o extrato.',
      { tipo: 'lista', itens: [
        'Horas extras viram crédito. Horas a menos usam primeiro o crédito mais antigo.',
        'Crédito não compensado no prazo vence e fica **a pagar** pela empresa.',
        'Dias incompletos ainda não entram no saldo: peça o ajuste.',
      ] },
      'Se aparecer "A jornada desta pessoa não usa banco de horas", as suas extras e atrasos ficam só no espelho do mês.',
    ],
  },
  {
    id: 'minha-escala',
    categoria: 'horas',
    publico: ['colaborador'],
    titulo: 'Minha escala',
    resumo: 'Para quem trabalha em 12x36 ou em escala: seus próximos turnos.',
    palavras: ['escala', 'turno', 'plantao', '12x36', 'folga', 'proximos dias'],
    telas: ['/espelho', '/gestao/meu-espelho'],
    corpo: [
      'Se você trabalha em escala, abra [Espelho](rota:espelho), aba **Minha escala**. Ela mostra os turnos e folgas dos próximos 21 dias, com feriados e afastamentos.',
      { tipo: 'dica', texto: 'Algo errado na escala? Fale com o RH da sua empresa: é ele quem monta.' },
    ],
  },
  {
    id: 'sininho',
    categoria: 'comecando',
    publico: ['colaborador', 'gestao'],
    titulo: 'Sininho de avisos',
    resumo: 'O que aparece no sininho e como marcar como lido.',
    palavras: ['sininho', 'aviso', 'notificacao', 'alerta', 'sino'],
    telas: [],
    corpo: [
      'O sininho, no alto da tela, mostra os avisos novos com um número vermelho. Toque nele para ver a lista. Tocar num aviso leva à tela certa e marca o aviso como lido.',
      { tipo: 'lista', itens: [
        'Resposta dos seus pedidos (aprovado ou recusado).',
        'Marcação faltando nos últimos dias.',
        'Foto de rosto aprovada ou recusada.',
        'Para gestor, RH e administrador: pedidos novos para analisar.',
        'Para RH e administrador: pessoa nova, foto para aprovar e banco de horas vencendo.',
      ] },
      { tipo: 'dica', texto: 'Use **Marcar todos como lidos** para limpar a lista de uma vez.' },
    ],
  },
  // ------------------------------------------------------------- Gestor
  {
    id: 'gestor-equipe',
    categoria: 'pessoas',
    publico: ['gestor'],
    titulo: 'Sou gestor: acompanhar a equipe e analisar pedidos',
    resumo: 'O que o gestor vê em Equipe e como aprovar ajustes e folgas.',
    palavras: ['gestor', 'equipe', 'lider', 'aprovar', 'recusar', 'time', 'supervisor'],
    telas: ['/equipe'],
    corpo: [
      'Se você é gestor de um departamento, o menu mostra **Equipe**, com as abas **Pedidos**, **Pessoas** e **Relatórios**. [Abrir Equipe](rota:equipe)',
      { tipo: 'sub', titulo: 'Analisar pedidos' },
      { tipo: 'passos', itens: [
        'Na aba **Pedidos**, veja os pendentes.',
        'Toque em **Aprovar** ou **Recusar**. Para recusar, explique o motivo: a pessoa lê a resposta.',
        'Confirme. A análise é definitiva e fica registrada com o seu nome.',
      ] },
      { tipo: 'lista', itens: [
        'Você analisa ajustes de marcação e folgas. Abonos com atestado vão direto para o RH.',
        'Os seus próprios pedidos vão para outra pessoa analisar.',
        'Em **Pessoas**, veja o espelho, as marcações, a escala e o banco de horas de cada um.',
        'Você não vê CPF, telefone nem atestados, e não altera cadastros ou escalas.',
      ] },
    ],
  },
  // ------------------------------------------------------------- Conta e acesso
  {
    id: 'entrar-convite',
    categoria: 'conta',
    publico: ['acesso'],
    titulo: 'Recebi um convite: como entrar',
    resumo: 'Criar a conta pelo link da empresa e começar a bater o ponto.',
    palavras: ['convite', 'link', 'codigo', 'primeiro acesso', 'criar conta', 'cadastro'],
    telas: ['/convite', '/onboarding'],
    corpo: [
      { tipo: 'passos', itens: [
        'Abra o link de convite que a empresa mandou.',
        'Preencha nome completo, CPF, e-mail e uma senha de pelo menos 6 caracteres, e toque em **Criar conta**.',
        'Abra o e-mail de confirmação e toque no link.',
        'Entre com o seu e-mail e senha.',
        'Se pedir, confirme o **Código de convite** e toque em **Entrar na empresa**.',
      ] },
      { tipo: 'dica', texto: 'Já tem conta? Entre normalmente e digite o código de convite que a empresa passou.' },
      { tipo: 'atencao', texto: 'Apareceu "Código de convite inválido"? Peça um link novo ao RH ou ao administrador da sua empresa.' },
    ],
  },
  {
    id: 'criar-empresa',
    categoria: 'conta',
    publico: ['acesso'],
    titulo: 'Cadastrar a minha empresa',
    resumo: 'Criar a conta de administrador e a empresa.',
    palavras: ['criar empresa', 'cadastrar empresa', 'administrador', 'comecar', 'teste'],
    telas: ['/criar-conta'],
    corpo: [
      { tipo: 'passos', itens: [
        'Na tela de entrada, toque em **Criar conta da minha empresa**.',
        'Preencha nome, CPF, e-mail e senha e confirme o e-mail.',
        'Entre e informe o nome da empresa (o CNPJ pode ficar para depois).',
        'Toque em **Criar empresa**. Você vira o administrador.',
      ] },
      'Depois, a lista **Primeiros passos**, na tela inicial, guia o resto da configuração.',
    ],
  },
  {
    id: 'esqueci-senha',
    categoria: 'conta',
    publico: ['acesso'],
    titulo: 'Esqueci minha senha',
    resumo: 'Receber um link por e-mail para criar uma senha nova.',
    palavras: ['senha', 'esqueci', 'recuperar', 'redefinir', 'nao consigo entrar', 'trocar senha'],
    telas: ['/entrar', '/recuperar-senha'],
    corpo: [
      { tipo: 'passos', itens: [
        'Na tela de entrada, toque em **Esqueci minha senha**.',
        'Digite o seu e-mail e toque em **Enviar link**.',
        'Abra o e-mail e toque no link.',
        'Escolha a nova senha e toque em **Salvar nova senha**.',
      ] },
      { tipo: 'atencao', texto: 'Apareceu "Link inválido ou expirado"? Toque em **Pedir um novo link** e use sempre o e-mail mais recente.' },
    ],
  },
  {
    id: 'nao-recebi-email',
    categoria: 'conta',
    publico: ['acesso'],
    titulo: 'Não recebi o e-mail',
    resumo: 'O e-mail de confirmação ou de senha não chegou.',
    palavras: ['email', 'nao chegou', 'confirmacao', 'spam', 'lixo eletronico', 'promocoes'],
    telas: ['/entrar', '/criar-conta', '/convite'],
    corpo: [
      { tipo: 'lista', itens: [
        'Espere alguns minutos: às vezes o e-mail demora.',
        'Procure nas pastas **Spam**, **Lixo eletrônico** e **Promoções**.',
        'Confira se o e-mail foi digitado certo.',
        'Para a senha, peça de novo em **Esqueci minha senha**. Use sempre o e-mail mais recente.',
      ] },
      'Se mesmo assim não chegar, fale com o RH da sua empresa ou com o suporte.',
    ],
  },
  {
    id: 'minha-conta',
    categoria: 'conta',
    publico: ['colaborador'],
    titulo: 'Mudar senha, nome e tema',
    resumo: 'O que dá para mudar em Minha conta.',
    palavras: ['minha conta', 'senha', 'nome', 'tema escuro', 'modo escuro', 'aparencia', 'sair'],
    telas: ['/conta', '/gestao/conta'],
    corpo: [
      'Em [Minha conta](rota:conta) você pode:',
      { tipo: 'lista', itens: [
        'corrigir o seu **nome** e tocar em **Salvar nome**;',
        'trocar a **senha** (pelo menos 6 caracteres);',
        'escolher o tema **Claro** ou **Escuro** (também pelo ícone de lua ou sol, no alto da tela);',
        'cadastrar o seu rosto, se a empresa usa reconhecimento facial;',
        'ligar ou desligar o **comprovante por e-mail**;',
        'sair da conta.',
      ] },
      'CPF, papel, unidade e situação só são alterados pelo RH ou pelo administrador.',
    ],
  },
  {
    id: 'instalar-app',
    categoria: 'conta',
    publico: ['colaborador'],
    titulo: 'Instalar o app no celular',
    resumo: 'Ter o Ayra Ponto na tela inicial, abrindo como um aplicativo.',
    palavras: ['app', 'aplicativo', 'instalar', 'tela inicial', 'icone', 'atalho', 'android', 'iphone', 'pwa', 'sem internet', 'offline'],
    telas: ['/conta', '/gestao/conta'],
    corpo: [
      'O Ayra Ponto pode ficar na tela do seu celular, com ícone próprio, e abre em tela cheia. Não precisa baixar nada da loja de aplicativos.',
      { tipo: 'sub', titulo: 'Android' },
      { tipo: 'passos', itens: [
        'Abra o Ayra Ponto no **Chrome**.',
        'Em [Minha conta](rota:conta), toque em **Instalar o app**. Se o botão não aparecer, toque nos três pontinhos do Chrome e em **Instalar app** (ou **Adicionar à tela inicial**).',
        'Confirme. O ícone aparece na tela do celular.',
      ] },
      { tipo: 'sub', titulo: 'iPhone' },
      { tipo: 'passos', itens: [
        'Abra o Ayra Ponto no **Safari**.',
        'Toque em **Compartilhar** (o quadrado com uma seta para cima).',
        'Toque em **Adicionar à Tela de Início** e depois em **Adicionar**.',
      ] },
      { tipo: 'atencao', texto: 'Para bater o ponto, o celular precisa estar com internet, mesmo com o app instalado. Sem conexão, o botão fica desativado: a hora e o número do registro (NSR) sempre vêm do servidor.' },
    ],
  },
  {
    id: 'privacidade',
    categoria: 'lei',
    publico: ['colaborador', 'gestao'],
    titulo: 'Privacidade e seus dados (LGPD)',
    resumo: 'Quem vê o quê e como os seus dados são protegidos.',
    palavras: ['lgpd', 'privacidade', 'dados pessoais', 'quem ve', 'seguranca', 'cpf', 'atestado', 'foto'],
    telas: [],
    corpo: [
      { tipo: 'lista', itens: [
        'Cada empresa só enxerga os próprios dados. Uma empresa nunca vê a outra.',
        'O colaborador vê as próprias marcações, pedidos e horas.',
        'O gestor vê as horas e os pedidos da equipe, mas não vê CPF, telefone nem atestados.',
        'Atestados só abrem para a própria pessoa, o RH e o administrador, por um link que vale poucos minutos.',
        'A foto de rosto é usada só para conferir quem bateu o ponto. O aviso **Como usamos o seu rosto** explica tudo antes do cadastro.',
        'As marcações ficam guardadas pelo tempo que a lei exige e não podem ser apagadas.',
      ] },
      'Dúvidas sobre os seus dados? Fale com o RH da sua empresa.',
    ],
  },
]

export default ARTIGOS_PESSOAIS
