// Artigos para o administrador e o RH.
// Formato do corpo: texto simples (parágrafo) ou blocos
//   { tipo: 'passos', itens: [...] }  { tipo: 'lista', itens: [...] }
//   { tipo: 'dica', texto }  { tipo: 'atencao', texto }  { tipo: 'sub', titulo }
// Dentro do texto: **negrito** e [texto](rota:chave) ou [texto](/gestao/...).

const ARTIGOS_GESTAO = [
  // ------------------------------------------------------------- Começando
  {
    id: 'primeiros-passos',
    categoria: 'comecando',
    publico: ['gestao'],
    titulo: 'Primeiros passos: deixar a empresa pronta',
    resumo: 'A ordem mais simples para configurar o Ayra Ponto do zero.',
    palavras: ['configurar', 'começar', 'inicio', 'implantar', 'checklist', 'lista'],
    telas: ['/gestao'],
    corpo: [
      'Na tela **Visão geral** aparece a lista **Primeiros passos**. Cada item leva direto à tela certa e fica marcado sozinho quando é feito. Você pode seguir na ordem que preferir. Esta é a ordem que costuma dar menos trabalho:',
      { tipo: 'passos', itens: [
        '**Dados da empresa:** razão social, CNPJ e endereço. Eles aparecem no espelho de ponto. [Abrir Empresa](/gestao/configuracoes/empresa)',
        '**Unidade:** confira o endereço e o fuso horário de cada local de trabalho. [Abrir Unidades](/gestao/configuracoes/unidades)',
        '**Jornada:** cadastre os horários de trabalho. Há modelos prontos, como Comercial 40h. [Abrir Jornadas](/gestao/jornadas)',
        '**Feriados:** o botão **Feriados nacionais** adiciona todos do ano de uma vez. [Abrir Feriados](/gestao/feriados)',
        '**Departamentos:** crie as áreas da empresa e, se quiser, escolha um gestor para cada uma. [Abrir Departamentos](/gestao/departamentos)',
        '**Convide a equipe:** envie o link de convite. Cada pessoa cria a própria senha.',
        '**Jornada de cada pessoa:** na ficha de cada pessoa, aba **Trabalho**, escolha a jornada ou a escala. [Abrir Colaboradores](/gestao/pessoas)',
        '**Primeira marcação:** registre você mesmo uma entrada e veja o comprovante. [Abrir Meu ponto](/gestao/meu-ponto)',
      ] },
      { tipo: 'dica', texto: 'Escondeu a lista e quer ver de novo? Na Central de ajuda, clique em **Mostrar os primeiros passos de novo**.' },
    ],
  },
  {
    id: 'convidar-equipe',
    categoria: 'comecando',
    publico: ['gestao'],
    titulo: 'Convidar a equipe',
    resumo: 'Como enviar o link de convite e o que acontece quando a pessoa entra.',
    palavras: ['convite', 'link', 'codigo', 'cadastrar funcionario', 'adicionar pessoa', 'novo colaborador'],
    telas: ['/gestao/pessoas', '/gestao/configuracoes/empresa'],
    corpo: [
      'Ninguém precisa ter a senha criada por você: cada pessoa cria a própria conta pelo link de convite.',
      { tipo: 'passos', itens: [
        'Abra [Colaboradores](/gestao/pessoas) e clique em **Convidar colaboradores**.',
        'Clique em **Copiar mensagem pronta** (ou **Copiar link**).',
        'Cole no WhatsApp ou no e-mail da pessoa e envie.',
        'A pessoa abre o link, preenche nome, CPF, e-mail e senha e confirma o e-mail.',
        'Pronto: ela aparece em Colaboradores e você recebe o aviso **Pessoa nova** no sininho.',
      ] },
      'Toda pessoa entra como **colaborador**, na unidade principal. Depois, abra a ficha dela para escolher a unidade, o departamento, o cargo, a jornada e, se for o caso, o papel (RH ou administrador).',
      { tipo: 'dica', texto: 'Quem já tem conta pode digitar o **código de convite** ao entrar. O código também aparece em [Empresa](/gestao/configuracoes/empresa), no cartão **Convite para a equipe**.' },
      { tipo: 'atencao', texto: 'Se o link foi parar com quem não devia, o administrador clica em **Gerar novo código**, em Empresa. O código antigo para de funcionar na hora, e quem já entrou continua na empresa.' },
    ],
  },
  {
    id: 'dados-empresa',
    categoria: 'comecando',
    publico: ['gestao'],
    titulo: 'Dados da empresa e CNPJ',
    resumo: 'Razão social, CNPJ e endereço: onde preencher e por que importam.',
    palavras: ['cnpj', 'razao social', 'endereco', 'inscricao', 'empresa', 'cep'],
    telas: ['/gestao/configuracoes/empresa'],
    corpo: [
      'Em [Empresa](/gestao/configuracoes/empresa) ficam o nome fantasia, a razão social, o CNPJ, as inscrições estadual e municipal, o contato e o endereço. Ao digitar o **CEP**, o endereço é preenchido sozinho.',
      'Esses dados aparecem no espelho de ponto e no comprovante de cada marcação.',
      { tipo: 'lista', itens: [
        'O CNPJ é conferido pelo dígito verificador e aceita o novo formato com letras.',
        'Enquanto o CNPJ gravado estiver inválido, a tela não salva outras mudanças: corrija o CNPJ primeiro.',
        'Só o administrador altera estes dados. O RH consegue consultar.',
      ] },
    ],
  },
  {
    id: 'unidades',
    categoria: 'comecando',
    publico: ['gestao'],
    titulo: 'Unidades (locais de trabalho)',
    resumo: 'Filiais, lojas ou obras: cada uma com endereço, fuso e numeração própria.',
    palavras: ['filial', 'loja', 'local', 'fuso horario', 'matriz', 'nsr', 'cei', 'cno', 'caepf'],
    telas: ['/gestao/configuracoes/unidades'],
    corpo: [
      'A empresa nasce com a unidade **Matriz**. Cadastre outras em [Unidades](/gestao/configuracoes/unidades), botão **Nova unidade**, com nome, documento (CNPJ, CEI, CAEPF ou CNO, se houver), endereço e **fuso horário**.',
      { tipo: 'lista', itens: [
        'Os horários das marcações aparecem no fuso da unidade da pessoa.',
        'Cada unidade tem a própria sequência de **NSR** (o número de cada marcação), como pede a Portaria 671.',
        'Não dá para desativar uma unidade que ainda tem pessoas, nem excluir uma que tem marcações.',
        'A empresa precisa ter pelo menos uma unidade ativa.',
        'Só o administrador cria e altera unidades.',
      ] },
    ],
  },
  {
    id: 'cerca-virtual',
    categoria: 'ponto',
    publico: ['gestao'],
    titulo: 'Cerca virtual e “ver no mapa”',
    resumo: 'Marque o local da unidade e veja quem registrou o ponto longe dele.',
    palavras: ['cerca', 'geolocalizacao', 'localizacao', 'mapa', 'gps', 'fora do local', 'raio', 'distancia', 'endereco'],
    telas: ['/gestao/configuracoes/unidades', '/gestao/pessoas'],
    corpo: [
      'A cerca virtual é um círculo ao redor da unidade. Quando alguém registra o ponto fora dele, a marcação ganha o selo **Fora do local**, com a distância. Serve só para o RH conferir: **o ponto nunca é bloqueado**, como manda a Portaria 671.',
      { tipo: 'sub', titulo: 'Ligar a cerca em uma unidade' },
      { tipo: 'passos', itens: [
        'Abra [Unidades](/gestao/configuracoes/unidades) e clique em **Editar** na unidade (só o administrador).',
        'No fim da janela, em **Localização e cerca virtual**, clique em **Buscar pelo endereço**. Se o ponto cair no lugar errado, **clique no mapa** onde fica a entrada.',
        'Se você estiver na unidade agora, o botão **Estou na unidade agora** marca o ponto pela localização do seu aparelho.',
        'Escolha o **raio**. O padrão é 200 metros; pode ir de 50 metros a 5 km.',
        'Clique em **Salvar alterações**. Para desligar, use **Desligar a cerca**.',
      ] },
      { tipo: 'sub', titulo: 'Ver as marcações' },
      'Na ficha da pessoa, aba **Marcações**, cada marcação fora da cerca mostra **Fora do local** e a distância. O ícone de mapa abre o local exato, com o círculo da cerca. Marcações sem localização aparecem como **Sem localização**.',
      { tipo: 'lista', itens: [
        'Cada marcação guarda o local e o raio **da época**: se você mudar a unidade de lugar, as marcações antigas não mudam.',
        'A localização vem do navegador ou do celular e pode errar por algumas dezenas de metros, e mais ainda em computadores. Trate como indício, não como prova.',
        'Em lugares grandes ou abertos (obra, fábrica, fazenda), use um raio maior.',
        'A pessoa recebe só um aviso gentil na hora da marcação; o ponto é registrado do mesmo jeito.',
        'Quem trabalha fora da unidade (visita, entrega) vai aparecer como fora do local. Isso é esperado.',
      ] },
      { tipo: 'atencao', texto: 'Avise a equipe que a localização é guardada junto de cada marcação e que o RH pode vê-la. É uma informação pessoal e deve constar na política de privacidade da empresa.' },
    ],
  },
  {
    id: 'regras-calculo',
    categoria: 'horas',
    publico: ['gestao'],
    titulo: 'Regras de cálculo e o resumo para o contador',
    resumo: 'Hora extra 50% e 100%, adicional noturno, intervalo, descanso de 11h e DSR: como o Ayra calcula.',
    palavras: ['regras', 'calculo', 'hora extra', '50%', '100%', 'noturno', 'adicional noturno', 'dsr', 'interjornada', 'intervalo', 'contador', 'folha', 'clt', 'convencao', '6x1', '44 horas'],
    telas: ['/gestao/configuracoes/regras', '/gestao/espelhos', '/gestao/pessoas'],
    corpo: [
      'Em [Regras de cálculo](/gestao/configuracoes/regras) ficam as regras que o espelho usa. **Já vem tudo no padrão da CLT**: só mude se a convenção coletiva ou o contador pedirem outro número. Só o administrador altera, e cada mudança fica no Histórico de alterações.',
      { tipo: 'sub', titulo: 'O que o espelho calcula' },
      { tipo: 'lista', itens: [
        '**Hora extra separada:** dias normais (padrão 50%) e domingo de descanso, feriado e folga trabalhados (padrão 100%). Na escala 12x36 o feriado já é compensado pela escala.',
        '**Horas noturnas:** das 22h às 5h, com a hora reduzida (52min30s valem 1 hora) e as horas depois das 5h de quem trabalhou a noite toda.',
        '**Intervalo a pagar:** quando o intervalo foi menor que o mínimo (1h para mais de 6h de trabalho; 15 min entre 4h e 6h). Se a equipe não marca o intervalo, ligue "intervalo pré-assinalado".',
        '**Descanso a pagar:** quando a pessoa descansou menos de 11h entre um dia e outro.',
        '**DSR perdido:** semana com falta sem justificativa (jornada semanal, descanso no domingo).',
        '**Semana acima do limite:** aviso quando a semana passa de 44h (ou do limite que você definir).',
      ] },
      'No espelho de cada pessoa aparece o cartão **Para o contador**, com os totais do mês, e cada dia mostra os avisos em português claro.',
      { tipo: 'dica', texto: 'Se a PEC do fim da escala 6x1 for aprovada, basta trocar o limite da semana para 42h e, depois, 40h.' },
      { tipo: 'atencao', texto: 'As horas aparecem no relógio (a hora reduzida entra só no total de horas noturnas). Combine com o contador como ele prefere receber.' },
    ],
  },
  // ------------------------------------------------------------- Pessoas
  {
    id: 'ficha-pessoa',
    categoria: 'pessoas',
    publico: ['gestao'],
    titulo: 'Editar o cadastro de uma pessoa',
    resumo: 'As abas da ficha: dados, trabalho, acesso, marcações, espelho e mais.',
    palavras: ['ficha', 'cadastro', 'editar', 'matricula', 'cpf', 'telefone', 'admissao', 'categoria', 'estagiario', 'aprendiz', 'trainee', 'clt'],
    telas: ['/gestao/pessoas'],
    corpo: [
      'Em [Colaboradores](/gestao/pessoas), clique no nome da pessoa para abrir a ficha. As abas são:',
      { tipo: 'lista', itens: [
        '**Dados:** nome, CPF, matrícula e telefone.',
        '**Trabalho:** unidade, departamento, cargo, como a pessoa trabalha (jornada semanal, escala 12x36 ou escala por calendário), data de admissão, categoria (CLT, Estagiário, Menor aprendiz ou Trainee) e situação.',
        '**Acesso:** o papel no sistema (Administrador, RH ou Colaborador).',
        '**Marcações, Espelho, Banco de horas, Afastamentos, Solicitações e Histórico:** tudo sobre a pessoa num lugar só.',
      ] },
      'Depois de mudar, clique em **Salvar alterações** (ou **Descartar** para desfazer).',
      { tipo: 'atencao', texto: 'O CPF precisa ter 11 números: ele aparece no comprovante de cada marcação. O telefone precisa de DDD.' },
      { tipo: 'dica', texto: 'Ninguém faz lançamentos de banco de horas nem registra afastamentos na própria ficha: outra pessoa precisa fazer.' },
    ],
  },
  {
    id: 'papeis',
    categoria: 'pessoas',
    publico: ['gestao'],
    titulo: 'Administrador, RH, gestor e colaborador: quem pode o quê',
    resumo: 'O que cada papel vê e faz no Ayra Ponto.',
    palavras: ['permissao', 'acesso', 'papel', 'perfil', 'rh', 'administrador', 'gestor', 'promover'],
    telas: ['/gestao/pessoas'],
    corpo: [
      { tipo: 'lista', itens: [
        '**Administrador:** acesso total. Cuida da empresa, das unidades, das pessoas e dos papéis.',
        '**RH:** cuida das pessoas, jornadas, escalas, pedidos e relatórios. Não altera a empresa, as unidades nem os papéis, e não altera o cadastro de um administrador.',
        '**Gestor:** é um colaborador escolhido em [Departamentos](/gestao/departamentos). Acompanha a equipe e aprova ou recusa ajustes e folgas dela. Não vê CPF, telefone nem atestados, e os abonos ficam com o RH.',
        '**Colaborador:** bate o ponto e acompanha as próprias horas e pedidos.',
      ] },
      'Para mudar o papel de alguém, o administrador abre a ficha da pessoa, aba **Acesso**. Ninguém muda o próprio papel.',
      { tipo: 'atencao', texto: 'Tornar alguém administrador dá acesso total à empresa. O sistema pede confirmação antes.' },
    ],
  },
  {
    id: 'desligar-pessoa',
    categoria: 'pessoas',
    publico: ['gestao'],
    titulo: 'Desligar uma pessoa',
    resumo: 'O que fazer quando alguém sai da empresa, sem perder o histórico.',
    palavras: ['demissao', 'desligamento', 'saiu', 'remover', 'excluir funcionario', 'inativar'],
    telas: ['/gestao/pessoas'],
    corpo: [
      { tipo: 'passos', itens: [
        'Abra a ficha da pessoa e vá na aba **Trabalho**.',
        'Em **Situação**, escolha **Desligado**.',
        'Clique em **Salvar alterações** e confirme em **Salvar mesmo assim**.',
      ] },
      'A partir daí, a pessoa não consegue mais registrar o ponto. **As marcações não são apagadas**: a lei exige que fiquem guardadas.',
      { tipo: 'dica', texto: 'Para ver quem saiu, use o filtro **Situação → Desligados** em Colaboradores. Nos relatórios, marque **Incluir pessoas desligadas** para fechar a folha de quem saiu no meio do mês.' },
    ],
  },
  {
    id: 'departamentos-gestores',
    categoria: 'pessoas',
    publico: ['gestao'],
    titulo: 'Departamentos, cargos e gestores',
    resumo: 'Organizar as áreas da empresa e escolher quem aprova os pedidos de cada equipe.',
    palavras: ['departamento', 'setor', 'area', 'gestor', 'lider', 'supervisor', 'cargo', 'funcao', 'equipe'],
    telas: ['/gestao/departamentos', '/gestao/cargos'],
    corpo: [
      { tipo: 'sub', titulo: 'Criar um departamento ou cargo' },
      'Em [Departamentos](/gestao/departamentos), clique em **Novo departamento**, dê um nome e salve. Em [Cargos](/gestao/cargos) é igual, com **Novo cargo**. Depois, escolha o departamento e o cargo na ficha de cada pessoa, aba **Trabalho**.',
      { tipo: 'sub', titulo: 'Escolher os gestores' },
      { tipo: 'passos', itens: [
        'Em Departamentos, clique em **Gestores** no departamento.',
        'Marque quem é gestor. Pode haver mais de um, e de qualquer departamento.',
        'Clique em **Salvar gestores**.',
      ] },
      'O gestor ganha o item **Equipe** no menu dele. Ali ele acompanha espelho, marcações, banco de horas e escala da equipe, e aprova ou recusa ajustes e folgas. Pedidos de abono continuam com o RH.',
      { tipo: 'dica', texto: 'Departamento sem gestor? Os pedidos daquela equipe vão para o RH e o administrador, em Solicitações.' },
      { tipo: 'atencao', texto: 'Não dá para excluir um departamento ou cargo que tem pessoas. Use **Desativar**.' },
    ],
  },
  // ------------------------------------------------------------- Jornada
  {
    id: 'jornadas',
    categoria: 'jornada',
    publico: ['gestao'],
    titulo: 'Criar uma jornada de trabalho',
    resumo: 'Horários da semana, intervalo, tolerância e banco de horas.',
    palavras: ['jornada', 'horario', 'expediente', 'carga horaria', 'intervalo', 'almoco', 'tolerancia', '44h', '40h', 'turno da noite'],
    telas: ['/gestao/jornadas'],
    corpo: [
      'A jornada diz o horário previsto de cada dia. É com ela que o Ayra calcula atrasos, faltas e horas extras.',
      { tipo: 'passos', itens: [
        'Abra [Jornadas](/gestao/jornadas) e clique em **Nova jornada**.',
        'Se quiser, comece de um modelo pronto: **Comercial 40h**, **Comercial 44h** ou **Estágio 30h**.',
        'Dê um nome e escolha a **Tolerância diária** (padrão: 10 minutos).',
        'Em **Horários da semana**, marque os dias de trabalho e preencha entrada, saída e intervalo. O botão **Copiar de Seg para os outros dias** economiza tempo.',
        'Se a empresa usa banco de horas, marque **Usar banco de horas nesta jornada** e escolha o prazo para compensar.',
        'Clique em **Salvar jornada**.',
      ] },
      'Depois, escolha a jornada na ficha de cada pessoa, aba **Trabalho**.',
      { tipo: 'dica', texto: 'Turno que vira a noite? Coloque a saída menor que a entrada (por exemplo, 22:00 às 06:00): o Ayra entende que termina no dia seguinte.' },
      { tipo: 'atencao', texto: 'Uma jornada usada por alguém não pode ser excluída. Use **Duplicar** para criar uma parecida.' },
    ],
  },
  {
    id: 'escala-12x36',
    categoria: 'jornada',
    publico: ['gestao'],
    titulo: 'Escala 12x36',
    resumo: 'Plantões de 12 horas com 36 de descanso, montados sozinhos.',
    palavras: ['12x36', 'plantao', 'escala', 'revezamento', 'turno'],
    telas: ['/gestao/escalas', '/gestao/pessoas'],
    corpo: [
      { tipo: 'passos', itens: [
        'Em [Escalas](/gestao/escalas), aba **Turnos**, confira se existe o turno do plantão (há prontos: **Plantão 12h dia** e **Plantão 12h noite**).',
        'Abra a ficha da pessoa, aba **Trabalho**.',
        'Em **Como a pessoa trabalha**, escolha **Escala 12x36**.',
        'Escolha o **Turno** e o **Primeiro dia de trabalho**.',
        'Clique em **Salvar alterações**. A ficha mostra os próximos plantões.',
      ] },
      'O Ayra monta os dias de trabalho e de folga sozinho. A pessoa vê os próximos turnos em **Espelho → Minha escala**.',
      { tipo: 'dica', texto: 'Mesmo em escala, escolha também uma jornada na ficha: dela vêm a tolerância e o banco de horas.' },
      { tipo: 'atencao', texto: 'Regras de feriado na 12x36 variam por convenção coletiva. Confira com o seu contador ou advogado.' },
    ],
  },
  {
    id: 'escala-calendario',
    categoria: 'jornada',
    publico: ['gestao'],
    titulo: 'Escala por calendário e turnos',
    resumo: 'Para quem trabalha em dias e turnos diferentes a cada mês.',
    palavras: ['escala', 'calendario', 'turno', 'folga', 'manha', 'tarde', 'noite', 'mes'],
    telas: ['/gestao/escalas'],
    corpo: [
      { tipo: 'sub', titulo: 'Turnos' },
      'Em [Escalas](/gestao/escalas), aba **Turnos**, clique em **Novo turno** e informe nome, sigla, entrada, saída e intervalo. Há turnos prontos (Manhã, Tarde, Noite e plantões).',
      { tipo: 'atencao', texto: 'Um turno já usado em dias passados não muda de horário. Crie um novo e desative o antigo.' },
      { tipo: 'sub', titulo: 'Montar o mês' },
      { tipo: 'passos', itens: [
        'Na ficha da pessoa, aba **Trabalho**, escolha **Escala por calendário** e salve.',
        'Em Escalas, aba **Calendário do mês**, escolha no topo o turno (ou **Folga**) que quer colocar.',
        'Clique nos dias de cada pessoa. Cada clique já fica salvo.',
        'Use **repetir semana** para copiar os dias 1 a 7 para o resto do mês.',
      ] },
      'A última linha, **Trabalham no dia**, mostra quantas pessoas trabalham em cada dia.',
    ],
  },
  {
    id: 'feriados',
    categoria: 'jornada',
    publico: ['gestao'],
    titulo: 'Feriados',
    resumo: 'Nacionais em um clique; estaduais, municipais e da empresa à mão.',
    palavras: ['feriado', 'ponto facultativo', 'carnaval', 'corpus christi', 'municipal', 'estadual'],
    telas: ['/gestao/feriados'],
    corpo: [
      'Em dia de feriado ninguém leva falta. Quem trabalha nesse dia tem as horas contadas.',
      { tipo: 'sub', titulo: 'Feriados nacionais' },
      'Em [Feriados](/gestao/feriados), clique em **Feriados nacionais**. Se quiser, marque **Incluir pontos facultativos** (Carnaval e Corpus Christi) e confirme. Só entram os que ainda não estão cadastrados.',
      { tipo: 'sub', titulo: 'Outros feriados' },
      'Clique em **Novo feriado**, informe data, tipo (Estadual, Municipal, Ponto facultativo ou Da empresa) e nome. Com mais de uma unidade, escolha em **Vale para** se é para todas ou só uma.',
      { tipo: 'dica', texto: 'Cadastre os feriados do ano logo no começo: eles mudam o cálculo do espelho de todo mundo.' },
    ],
  },
  // ------------------------------------------------------------- Horas
  {
    id: 'horas-equipe',
    categoria: 'horas',
    publico: ['gestao'],
    titulo: 'Horas da equipe e espelho de cada pessoa',
    resumo: 'Previsto, trabalhado, atrasos, faltas e extras do mês.',
    palavras: ['horas', 'espelho', 'folha', 'fechamento', 'extras', 'faltas', 'atrasos', 'mes', 'planilha'],
    telas: ['/gestao/espelhos'],
    corpo: [
      'Em [Horas da equipe](/gestao/espelhos) você vê o mês de cada pessoa: previsto, trabalhado, atrasos, faltas, extras e avisos.',
      { tipo: 'lista', itens: [
        'Use as setas para mudar o mês e os filtros para buscar alguém ou um departamento.',
        'Clique no nome para abrir o espelho completo da pessoa.',
        '**Baixar planilha** gera um arquivo que abre no Excel.',
        'No espelho da pessoa, **Imprimir ou salvar em PDF** gera a folha para assinatura.',
      ] },
      { tipo: 'dica', texto: 'A coluna **Avisos** mostra dias que pedem atenção, como marcação sem par ou intervalo curto. Peça para a pessoa fazer o ajuste.' },
    ],
  },
  {
    id: 'banco-horas-gestao',
    categoria: 'horas',
    publico: ['gestao'],
    titulo: 'Banco de horas: como funciona e lançamentos',
    resumo: 'Ligar o banco, acompanhar vencimentos e lançar compensações e pagamentos.',
    palavras: ['banco de horas', 'compensacao', 'saldo', 'vencimento', 'pagamento', 'horas extras', 'credito'],
    telas: ['/gestao/banco-de-horas'],
    corpo: [
      'O banco é ligado na **jornada** (Jornadas → editar → **Usar banco de horas nesta jornada**), com o prazo para compensar (de 1 a 12 meses).',
      { tipo: 'lista', itens: [
        'Horas extras viram crédito. Horas a menos consomem primeiro o crédito mais antigo.',
        'Crédito não compensado no prazo vence e fica **a pagar**.',
        'Em [Banco de horas](/gestao/banco-de-horas) você vê o saldo de cada pessoa, o que vence em 30 dias e o que já venceu.',
        'Toda semana, o sininho avisa o RH e o administrador sobre horas vencendo.',
      ] },
      { tipo: 'sub', titulo: 'Fazer um lançamento' },
      { tipo: 'passos', itens: [
        'Abra a ficha da pessoa, aba **Banco de horas**, e clique em **Novo lançamento**.',
        'Escolha o tipo: **Saldo inicial**, **Compensação**, **Pagamento em folha** ou **Ajuste**.',
        'Informe as horas, o dia e o motivo, e clique em **Registrar lançamento**.',
      ] },
      { tipo: 'atencao', texto: 'Lançamentos não podem ser editados nem apagados. Para corrigir, faça um **Ajuste** no sentido contrário.' },
    ],
  },
  {
    id: 'afastamentos',
    categoria: 'horas',
    publico: ['gestao'],
    titulo: 'Férias, atestados e afastamentos',
    resumo: 'Registrar períodos em que a pessoa não trabalha, sem virar falta.',
    palavras: ['ferias', 'atestado', 'licenca', 'inss', 'afastamento', 'maternidade', 'medico'],
    telas: ['/gestao/pessoas'],
    corpo: [
      { tipo: 'passos', itens: [
        'Abra a ficha da pessoa, aba **Afastamentos**, e clique em **Registrar afastamento**.',
        'Escolha o tipo: Férias, Atestado médico, Licença, Afastamento pelo INSS ou Outro afastamento.',
        'Informe o primeiro e o último dia.',
        'Se quiser, anexe o atestado ou documento (PDF ou foto, até 5 MB).',
        'Clique em **Registrar**.',
      ] },
      'Nos dias do afastamento não há falta, e o espelho mostra o motivo.',
      { tipo: 'atencao', texto: 'Não escreva diagnóstico nem CID na observação. O anexo só abre para a própria pessoa, o RH e o administrador.' },
      { tipo: 'dica', texto: 'Registrou errado? Clique em **Cancelar afastamento** e informe o motivo. Os dias voltam a contar normalmente.' },
    ],
  },
  // ------------------------------------------------------------- Pedidos
  {
    id: 'analisar-pedidos',
    categoria: 'pedidos',
    publico: ['gestao'],
    titulo: 'Aprovar ou recusar pedidos',
    resumo: 'Ajustes de marcação, abonos e folgas: como analisar e o que acontece depois.',
    palavras: ['solicitacao', 'pedido', 'aprovar', 'recusar', 'ajuste', 'abono', 'folga', 'correcao', 'esquecida'],
    telas: ['/gestao/solicitacoes'],
    corpo: [
      'Os pedidos chegam em [Solicitações](/gestao/solicitacoes), e o sininho avisa. O número no menu mostra quantos esperam.',
      { tipo: 'passos', itens: [
        'Na aba **Pendentes**, leia o pedido. Se houver atestado, clique em **Ver atestado**.',
        'Clique em **Aprovar** ou **Recusar**.',
        'Para recusar, escreva o motivo (obrigatório). Para aprovar, o comentário é opcional.',
        'Confirme. A pessoa recebe a resposta no sininho.',
      ] },
      { tipo: 'lista', itens: [
        'A análise é definitiva e fica registrada com o seu nome e o horário.',
        'A marcação original **nunca é apagada**. O ajuste aprovado entra no cálculo, e o espelho mostra um lápis.',
        'Ninguém analisa o próprio pedido.',
        'Gestores analisam ajustes e folgas da equipe deles. Abonos são sempre do RH e do administrador.',
        'Se duas pessoas analisarem ao mesmo tempo, vale a primeira.',
      ] },
    ],
  },
  // ------------------------------------------------------------- Relatórios
  {
    id: 'relatorios',
    categoria: 'relatorios',
    publico: ['gestao', 'gestor'],
    titulo: 'Relatórios e planilhas',
    resumo: 'Frequência, pedidos, banco de horas e marcações, para baixar ou imprimir.',
    palavras: ['relatorio', 'planilha', 'excel', 'pdf', 'imprimir', 'frequencia', 'marcacoes', 'folha de pagamento'],
    telas: ['/gestao/relatorios', '/equipe'],
    corpo: [
      'Em [Relatórios](/gestao/relatorios) (para o gestor: **Equipe → Relatórios**) há quatro relatórios:',
      { tipo: 'lista', itens: [
        '**Frequência:** horas previstas e trabalhadas, atrasos, faltas e extras, por pessoa ou por dia (até 3 meses).',
        '**Pedidos:** quantos chegaram, foram aprovados ou recusados, e o tempo médio de resposta.',
        '**Banco de horas:** o saldo de cada pessoa na data que você escolher.',
        '**Marcações:** todas as marcações do período, com NSR e unidade (até 62 dias).',
      ] },
      'Escolha o período (há botões prontos, como **Mês passado**) e clique em **Baixar planilha** ou **Imprimir ou PDF**.',
      { tipo: 'dica', texto: 'Na planilha, as horas vêm em número decimal: 1,50 quer dizer 1h30.' },
    ],
  },
  {
    id: 'historico-alteracoes',
    categoria: 'relatorios',
    publico: ['gestao'],
    titulo: 'Histórico de alterações',
    resumo: 'Quem mudou o quê e quando, sem possibilidade de apagar.',
    palavras: ['historico', 'auditoria', 'log', 'quem alterou', 'mudanca', 'registro'],
    telas: ['/gestao/historico'],
    corpo: [
      'Em [Histórico de alterações](/gestao/historico), cada linha conta quem criou, alterou ou excluiu algo e quando: cadastros, pedidos, jornadas, escalas, afastamentos, banco de horas, departamentos, empresa, unidades e reconhecimento facial.',
      { tipo: 'lista', itens: [
        'Filtre por período, pelo tipo de mudança ou pelo nome.',
        'Na ficha de cada pessoa, a aba **Histórico** mostra só as mudanças dela.',
        'Ninguém consegue apagar nem editar o histórico, nem o administrador.',
        'CPF e telefone aparecem só como "(alterado)".',
        'Só o administrador e o RH veem o histórico.',
      ] },
      { tipo: 'dica', texto: 'As marcações de ponto não aparecem aqui porque têm o registro próprio, com NSR, que nunca muda.' },
    ],
  },
  // ------------------------------------------------------------- Facial
  {
    id: 'ligar-facial',
    categoria: 'facial',
    publico: ['gestao'],
    titulo: 'Ligar o reconhecimento facial',
    resumo: 'Foto no momento da marcação, para conferir quem bateu o ponto.',
    palavras: ['reconhecimento facial', 'rosto', 'foto', 'selfie', 'biometria', 'ligar'],
    telas: ['/gestao/configuracoes/empresa', '/gestao/reconhecimento'],
    corpo: [
      'Com o reconhecimento facial ligado, a câmera tira uma foto na hora da marcação e compara com a foto de cadastro da pessoa.',
      { tipo: 'passos', itens: [
        'Em [Empresa](/gestao/configuracoes/empresa), no cartão **Ponto com reconhecimento facial**, clique em **Ligar reconhecimento facial** e confirme.',
        'Avise a equipe e peça para cada pessoa cadastrar o rosto em **Minha conta**.',
        'Aprove as fotos em [Reconhecimento facial](/gestao/reconhecimento), aba **Fotos para aprovar**.',
      ] },
      { tipo: 'atencao', texto: 'O reconhecimento facial **nunca impede o ponto**. Sem câmera ou sem reconhecer o rosto, a marcação é registrada igual e fica para o RH conferir.' },
      'Só o administrador liga ou desliga esse recurso.',
    ],
  },
  {
    id: 'conferir-facial',
    categoria: 'facial',
    publico: ['gestao'],
    titulo: 'Aprovar fotos e conferir marcações',
    resumo: 'O que fazer com as fotos de cadastro e as marcações sem rosto reconhecido.',
    palavras: ['aprovar foto', 'conferir', 'contestar', 'rosto nao reconhecido', 'integridade'],
    telas: ['/gestao/reconhecimento'],
    corpo: [
      { tipo: 'sub', titulo: 'Fotos para aprovar' },
      'Compare a foto nova com a pessoa. Clique em **Aprovar** ou em **Recusar**, escolhendo um motivo (por exemplo, "Foto escura" ou "Não é a pessoa"). A pessoa recebe o aviso no sininho.',
      { tipo: 'sub', titulo: 'Marcações a conferir' },
      'Aparecem as marcações em que o rosto não foi confirmado, com a foto da marcação ao lado da foto de cadastro. Clique em **Era a pessoa** ou em **Não era** (com uma explicação). A marcação nunca é apagada: fica registrada como conferida ou contestada.',
      { tipo: 'dica', texto: 'O cartão **Integridade das marcações**, botão **Conferir agora**, confirma que nenhuma marcação foi alterada.' },
      'O RH não analisa as próprias fotos nem as de um administrador.',
    ],
  },
  {
    id: 'arquivos-fiscais',
    categoria: 'lei',
    publico: ['gestao'],
    titulo: 'Arquivos fiscais: AFD e AEJ',
    resumo: 'O que são, quando a fiscalização pede e como baixar.',
    palavras: ['afd', 'aej', 'fiscalizacao', 'auditor', 'ministerio do trabalho', 'arquivo fonte de dados', 'arquivo eletronico de jornada', 'portaria 671', 'nsr'],
    telas: ['/gestao/arquivos-fiscais'],
    corpo: [
      'Numa fiscalização, o auditor do trabalho pode pedir dois arquivos, no formato oficial da Portaria 671:',
      { tipo: 'lista', itens: [
        '**AFD (Arquivo Fonte de Dados):** todas as marcações **exatamente como foram feitas**, em ordem de NSR, com o código de integridade de cada uma. Também traz os cadastros da empresa e das pessoas no ponto. Ajustes aprovados **não** mudam o AFD.',
        '**AEJ (Arquivo Eletrônico de Jornada):** a jornada **já tratada**: horários contratuais, marcações com os ajustes aprovados (a original aparece como desconsiderada, e a nova com o motivo), faltas e movimentos do banco de horas.',
      ] },
      { tipo: 'sub', titulo: 'Como baixar' },
      { tipo: 'passos', itens: [
        'Abra [Arquivos fiscais](/gestao/arquivos-fiscais), no menu Gestão.',
        'Se houver mais de uma unidade, escolha a unidade: cada uma tem a própria sequência de NSR e o próprio arquivo.',
        'Escolha o período (há os botões **Este mês** e **Mês passado**).',
        'Clique em **Baixar AFD** ou **Baixar AEJ**. Vem um arquivo .zip com o arquivo de texto e a assinatura digital (.p7s), que devem ser entregues juntos.',
      ] },
      { tipo: 'lista', itens: [
        'O AFD pode ter até 1 ano por arquivo; o AEJ, até 3 meses (gere em partes, se precisar).',
        'Só o administrador e o RH baixam esses arquivos.',
        'O CNPJ da empresa precisa estar cadastrado em [Empresa](/gestao/configuracoes/empresa).',
      ] },
      { tipo: 'atencao', texto: 'O arquivo .p7s é a assinatura digital ICP-Brasil (padrão CAdES) do arquivo de texto. Entregue os dois juntos e não altere o texto: qualquer mudança invalida a assinatura e o código de integridade.' },
    ],
  },
  {
    id: 'portaria-671',
    categoria: 'lei',
    publico: ['gestao'],
    titulo: 'O Ayra Ponto e a Portaria 671',
    resumo: 'Como o sistema registra o ponto e protege as marcações.',
    palavras: ['portaria 671', 'lei', 'rep-p', 'nsr', 'fiscalizacao', 'mte', 'legal', 'clt', 'comprovante'],
    telas: [],
    corpo: [
      'O Ayra Ponto é um registro de ponto por programa (REP-P), a categoria da Portaria 671/2021 do Ministério do Trabalho. Na prática:',
      { tipo: 'lista', itens: [
        'O horário de cada marcação vem do servidor, nunca do relógio do celular.',
        'Cada marcação recebe um **NSR** (número sequencial por unidade) e um código de integridade.',
        'Marcações **nunca são apagadas nem alteradas**. Correções viram pedidos de ajuste, aprovados por outra pessoa, e a marcação original fica guardada.',
        'A pessoa recebe um comprovante a cada marcação.',
        'O sistema nunca impede a marcação por causa da localização, da câmera ou da sugestão de tipo.',
        'Os arquivos oficiais **AFD** e **AEJ** são gerados em [Arquivos fiscais](/gestao/arquivos-fiscais).',
      ] },
      { tipo: 'atencao', texto: 'Regras de jornada, banco de horas e feriados podem variar conforme o acordo ou a convenção coletiva da sua categoria. Em caso de dúvida, confirme com o seu contador ou advogado trabalhista.' },
    ],
  },
]

export default ARTIGOS_GESTAO
